# Generated by Django 5.0.3 on 2024-05-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0027_solution_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('therapist', 'Therapist')], default='therapist'),
        ),
    ]
